name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setuping .env files
        run: echo "${{ secrets.APP_CONFIG_ENV }}" > etc/.env.prod

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Build the Retailer Admin
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/Dockerfile
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/retailer-admin:${{ steps.commit.outputs.short }}